### ISSUE TITLE
switches problem

### ISSUE THREAD

**Issue by DAVIZINH0** [w1tw0lf/Unifi-Device-info#10]
Hello.
Exist a list of switches than the scripts works?

I have:
- 1 gateway ultra
- 1 poe max 16 switch
- 1 switch flex mini 2.5
- 1 switch flex mini

and I dont obtain information of any or this devices :-(
maybe its may frault :-(

**Comment by w1tw0lf** [comment]
Need a bit more info, might be related to #9 ?

**Comment by DAVIZINH0** [comment]
yes, i think its probable the same. a lot of devices causes problem.
i will test the other script! thanks!!!

**Comment by w1tw0lf** [comment]
Lets continue on #9
