### ISSUE TITLE
Script fails since HA update

### ISSUE THREAD

**Issue by nightfever77** [w1tw0lf/Unifi-Device-info#2]
Script stopped working for me since the latest HA major update:

`Logger: homeassistant.components.command_line
Source: components/command_line/__init__.py:44
Integration: command_line (documentation, issues)
First occurred: 1. Juli 2022 um 18:27:37 (462 occurrences)
Last logged: 09:49:40

Command failed: python3 /config/scripts/unifi_ap.py`

**Comment by w1tw0lf** [comment]
Not experiencing any issue on my side. On the latest version as well.

Did you perhaps change anything on unifi side, maybe changed password ?
