### ISSUE TITLE
Error 405 connecting to Controller

### ISSUE THREAD

**Issue by davyvr** [w1tw0lf/Unifi-Device-info#4]
I'm trying to get this working, but I'm stuck on the login it seems, and I don't have a clue how to solve it.

My Home Assistant (2023.5.3) is running in a Docker image on my NAS (Synology DS418 play with DSM7), which has IP address 192.168.0.2. The Unifi Controller (7.3.83) is running in another Docker image on the same NAS. Both are running fine.

I've followed the instructions from the Readme to get the integration going for 2 AP's, but when I look at the sensors in Home Assistant they are all in status "Unknown". So I've tried to run the script for one of the AP's from a terminal window using the command:
'python3 /config/scripts/unifi_ap_liv.py'
and the result is this:

```
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: Insecure
RequestWarning: Unverified HTTPS request is being made to host '192.168.0.2'. Ad
ding certificate verification is strongly advised. See: https://urllib3.readthed
ocs.io/en/1.26.x/advanced-usage.html#ssl-warnings                               
  warnings.warn(                                                                
Traceback (most recent call last):                                              
  File "/config/scripts/unifi_ap_liv.py", line 21, in <module>                  
    client = Controller(host, username, password, port, version,                
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 113
, in __init__                                                                   
    self._login()                                                               
  File "/usr/local/lib/python3.10/site-packages/pyunifi/controller.py", line 195
, in _login                                                                     
    raise APIError(                                                             
pyunifi.controller.APIError: Login failed - status code: 405  
```

So first I get a warning about SSL, which I don't mind. But it seems I get an HTTP error 405, and I have no idea why.

Here is my config:

```
host = '192.168.0.2'
username = 'davyvr'
password = 'XXXXXXXXX'
version = 'UDMP-unifiOS'
#### version ####
## the base version of the controller API [v4|v5|unifiOS|UDMP-unifiOS] ##
## this would be for the version of the controller you are running ##
#################
site_id = 'default'
port = '8443'
verify_ssl = False
target_mac = 'fc:ec:da:16:c8:8f'
```

Any suggestions as to what I could try? How to get this solved?

Thanks in advance,
Davy

**Comment by w1tw0lf** [comment]
Thinking you need to change the version, as docker is not UDMP-unifiOS, try either v4 or v5.

**Comment by davyvr** [comment]
v5 indeed, thanks for the hint! Now to try and install the card

**Comment by w1tw0lf** [comment]
Pleasure.
