### ISSUE TITLE
is pyunifi required?

### ISSUE THREAD

**Issue by JamesMarcum** [w1tw0lf/Unifi-Device-info#7]
https://github.com/finish06/pyunifi - Is this required to get it to work?  I have hassio (home assistant) so I cannot use PIP.  No idea how to install this thing!  Any pointers?

**Comment by JamesMarcum** [comment]
Nevermind - not compatible with HASSIO as far as I can tell.  Command line python3 not supported.

**Comment by w1tw0lf** [comment]
Please make sure you have https://github.com/custom-components/sensor.unifigateway setup and running as per the readme to get it to work.

**Comment by JamesMarcum** [comment]
I do.  Problem is that HASSIO version of HA does not support python3 command line.  Scripts need to be defined as functions instead of called.  Unless there is a way around that that is beyond me.

**Comment by w1tw0lf** [comment]
If you follow the instructions it will work. I am running it on home assistant os without any issues.

The only thing is the way the command line is done has changed in 2023.6.
